/**
 * Master Business Document Register for Opus Care Support Services
 * Complete 85-item register across 15 operational categories.
 */

export type DocumentCategory =
  | '1. Participant & Client Documents'
  | '2. Workforce & Employment Documents'
  | '3. Contractor Documents'
  | '4. Payroll & Pay Documents'
  | '5. Finance & Billing Documents'
  | '6. Service Delivery Records'
  | '7. Safeguarding & Quality Records'
  | '8. WHS & Safety Records'
  | '9. Vehicle & Transport Records'
  | '10. Governance & Business Operational Documents'
  | '11. Regulatory & Unregistered Provider Evidence'
  | '12. Continuous Improvement & Audit Evidence'
  | '13. Marketing, Public & Information Notices'
  | '14. Training & Competency Records'
  | '15. Clinical & High-Intensity Transition Documents';

export type DocumentClass =
  | 'A. GENERATED DOCUMENT'
  | 'B. CRM STRUCTURED RECORD / FORM'
  | 'C. CONTROLLED POLICY'
  | 'D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT'
  | 'E. EVIDENCE / UPLOADED DOCUMENT';

export const DOCUMENT_CATEGORIES: DocumentCategory[] = [
  '1. Participant & Client Documents',
  '2. Workforce & Employment Documents',
  '3. Contractor Documents',
  '4. Payroll & Pay Documents',
  '5. Finance & Billing Documents',
  '6. Service Delivery Records',
  '7. Safeguarding & Quality Records',
  '8. WHS & Safety Records',
  '9. Vehicle & Transport Records',
  '10. Governance & Business Operational Documents',
  '11. Regulatory & Unregistered Provider Evidence',
  '12. Continuous Improvement & Audit Evidence',
  '13. Marketing, Public & Information Notices',
  '14. Training & Competency Records',
  '15. Clinical & High-Intensity Transition Documents',
];

export const DOCUMENT_CLASSES: DocumentClass[] = [
  'A. GENERATED DOCUMENT',
  'B. CRM STRUCTURED RECORD / FORM',
  'C. CONTROLLED POLICY',
  'D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT',
  'E. EVIDENCE / UPLOADED DOCUMENT',
];

export type DocumentAudience =
  | 'Participant / Nominee'
  | 'Support Worker'
  | 'Contractor'
  | 'Admin / Operations'
  | 'Plan Manager / NDIA'
  | 'Public / All';

export type RegisterStatus =
  | 'READY'
  | 'PARTIAL'
  | 'MISSING'
  | 'EXTERNAL-OFFICIAL'
  | 'NOT-APPLICABLE'
  | 'FUTURE / CLINICAL-DISABLED';

export interface MasterDocumentItem {
  code: string;
  name: string;
  category: DocumentCategory;
  documentClass: DocumentClass;
  audience: DocumentAudience;
  mandatoryStatus: 'Mandatory' | 'Conditional' | 'Optional' | 'Future';
  trigger: string;
  owner: string;
  version: string;
  effectiveDate: string;
  reviewDate: string;
  acknowledgementRequired: boolean;
  signatureRequired: boolean;
  retentionRecordStatus: string;
  systemLocation: string;
  officialUrl?: string;
  templateAvailable: boolean;
  generationAvailable: boolean;
  storageAvailable: boolean;
  status: RegisterStatus;
  notes?: string;
}

export const MASTER_DOCUMENT_REGISTER: MasterDocumentItem[] = 
[
  {
    "code": "DOC-PART-01",
    "name": "NDIS Service Agreement",
    "category": "1. Participant & Client Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Intake and onboarding completion prior to service delivery",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service (or age 25 if child)",
    "systemLocation": "/admin (Agreements tab) / documents (Signed storage)",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Permanent employment contract template clauses available; casual agreement DOC-WRK-01 is actively seeded in database. Records stored in public.documents under category employment_contract."
  },
  {
    "code": "DOC-PART-02",
    "name": "Schedule of Supports",
    "category": "1. Participant & Client Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Service agreement execution and plan budget allocation",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "/admin (Agreements tab) / documents (Signed storage)",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-03",
    "name": "Participant Intake & Support Plan Assessment Record",
    "category": "1. Participant & Client Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Initial intake and support coordination onboarding",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.participants / CRM Participant Profile",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY",
    "notes": "Statutory payslips generated by external STP engine are uploaded to public.documents under category payslip with strict RLS isolation per worker."
  },
  {
    "code": "DOC-PART-04",
    "name": "Home Environment & Individual Risk Assessment",
    "category": "1. Participant & Client Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to first home visit / shift commencement",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.risk_assessments / Admin Risk Assessments Tab & /api/governance/whs",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-05",
    "name": "Consent & Information Sharing Authority",
    "category": "1. Participant & Client Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "During intake onboarding and before communicating with nominees/providers",
    "owner": "Privacy Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.controlled_documents (DOC-ISA-01) / /documents/information-sharing",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-06",
    "name": "Advocacy, Rights & Decision-Making Record",
    "category": "1. Participant & Client Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Delivered at onboarding pack and available continuously",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.controlled_documents (DOC-RGT-01) / /documents/rights-and-responsibilities",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-07",
    "name": "Participant Welcome Pack & Handbook",
    "category": "1. Participant & Client Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Delivered digitally or in print upon service agreement confirmation",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Controlled document register history",
    "systemLocation": "public.controlled_documents (DOC-HBK-01) / /documents/welcome-pack",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-08",
    "name": "Emergency & Evacuation Plan (Individual)",
    "category": "1. Participant & Client Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Service commencement and after-hours triage agreement",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.controlled_documents (DOC-EMG-01) / /documents/emergency-support",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-09",
    "name": "Service Exit & Transition Notice",
    "category": "1. Participant & Client Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Conditional",
    "trigger": "Participant exit, handover to new provider, or service cessation (14 days notice)",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.controlled_documents (DOC-EXT-01) / /documents/exit-transition",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PART-10",
    "name": "Participant Goal Tracking & Support Plan Review",
    "category": "1. Participant & Client Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "End of each completed shift / periodic quarterly plan review",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.participant_goals / CRM Goals tab & Worker Portal",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WRK-01",
    "name": "Casual Employment Contract (SCHADS Award)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Recruitment and onboarding of casual support workers",
    "owner": "HR / Workforce Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-employment termination",
    "systemLocation": "public.document_templates (DOC-WRK-01) / documents table",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WRK-02",
    "name": "Permanent Employment Contract (SCHADS Award)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Conditional",
    "trigger": "Hiring permanent full-time/part-time operational staff",
    "owner": "HR / Workforce Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-employment termination",
    "systemLocation": "public.documents (category: employment_contract) / Admin Agreements",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Permanent employment contract template clauses available; casual agreement DOC-WRK-01 is actively seeded in database. Records stored in public.documents under category employment_contract."
  },
  {
    "code": "DOC-WRK-03",
    "name": "Fair Work Information Statement (FWIS)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Must be given to every new employee before, or as soon as possible after, starting work",
    "owner": "Fair Work Ombudsman",
    "version": "Current (Fair Work Act 2009 s125)",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual Fair Work review",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "Official Fair Work delivery / Worker Readiness Panel credential tracking",
    "officialUrl": "https://www.fairwork.gov.au/employment-conditions/national-employment-standards/fair-work-information-statement",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-WRK-04",
    "name": "Casual Employment Information Statement (CEIS)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Must be given to every casual employee before, or as soon as possible after, starting work",
    "owner": "Fair Work Ombudsman",
    "version": "Current (Fair Work Act 2009 s125B)",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual Fair Work review",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "Official Fair Work delivery / Worker Readiness Panel credential tracking",
    "officialUrl": "https://www.fairwork.gov.au/employment-conditions/national-employment-standards/casual-employment-information-statement",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-WRK-05",
    "name": "Fixed Term Contract Information Statement (FTCIS)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Conditional",
    "trigger": "Must be given to employees entering fixed-term employment contracts",
    "owner": "Fair Work Ombudsman",
    "version": "Current (Fair Work Act 2009 s333J)",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual Fair Work review",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "Official Fair Work delivery / Worker Readiness Panel credential tracking",
    "officialUrl": "https://www.fairwork.gov.au/employment-conditions/national-employment-standards/fixed-term-contract-information-statement",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-WRK-06",
    "name": "ATO Tax File Number Declaration (NAT 3092)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Completed by employee upon hire; forwarded directly to external STP payroll",
    "owner": "Australian Taxation Office (ATO)",
    "version": "NAT 3092 (Current)",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual ATO update",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "Maintained in external STP payroll provider; Privacy Rule: No TFN stored in CRM",
    "systemLocation": "Official ATO Form / Worker Readiness Panel compliance record",
    "officialUrl": "https://www.ato.gov.au/forms-and-instructions/tax-file-number-declaration",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "EXTERNAL-OFFICIAL",
    "notes": "Privacy Rule: Never store raw TFNs, completed forms, or scans in CRM. TFN declarations belong directly in the external compliant STP payroll engine. Opus CRM tracks only the boolean compliance flag (tfn_declaration_collected)."
  },
  {
    "code": "DOC-WRK-07",
    "name": "ATO Superannuation Standard Choice Form (NAT 13080)",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Employee nominates superannuation fund or default fund within 28 days of hire",
    "owner": "Australian Taxation Office (ATO)",
    "version": "NAT 13080 (Current)",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual ATO update",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "5 years post-submission",
    "systemLocation": "Official ATO Form / Uploaded to documents (category: super_choice)",
    "officialUrl": "https://www.ato.gov.au/forms-and-instructions/super-fund-standard-choice-form",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-WRK-08",
    "name": "Worker Position Description & Competency Profile",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Staff profile creation and roster role assignment",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.staff / Admin Staff Management",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WRK-09",
    "name": "Worker Onboarding Induction Checklist",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to roster activation (enforced by rosterable gate)",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (whs_induction) / Worker Readiness Panel",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WRK-10",
    "name": "NDIS Worker Code of Conduct Agreement",
    "category": "2. Workforce & Employment Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory onboarding acknowledgment prior to first shift",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.controlled_documents (DOC-COC-01) / /documents/worker-code-of-conduct",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CTR-01",
    "name": "Subcontractor / Independent Contractor Agreement",
    "category": "3. Contractor Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Contractor",
    "mandatoryStatus": "Conditional",
    "trigger": "Engagement of independent allied health or external specialist contractors",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-engagement termination",
    "systemLocation": "public.document_templates (DOC-CTR-01) / documents table",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CTR-02",
    "name": "Contractor ABN & Business Registration Verification",
    "category": "3. Contractor Documents",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Contractor",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to contractor engagement and payment",
    "owner": "Finance Lead",
    "version": "1.0",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual ABR check",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-engagement",
    "systemLocation": "public.documents (owner_type: contractor, category: abn_verification)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CTR-03",
    "name": "Contractor Certificate of Currency (Public Liability & PI)",
    "category": "3. Contractor Documents",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Contractor",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to commencement and annually upon policy expiry",
    "owner": "Operations Lead",
    "version": "Annual",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Policy expiry date",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-engagement",
    "systemLocation": "public.documents (owner_type: contractor, category: insurance_coc)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CTR-04",
    "name": "Contractor NDIS Worker Screening Verification",
    "category": "3. Contractor Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Contractor",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to participant interaction",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Screening expiry date",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-engagement",
    "systemLocation": "public.worker_credentials (requirement_code: ndis_worker_screening)",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CTR-05",
    "name": "Contractor Code of Conduct & Confidentiality Undertaking",
    "category": "3. Contractor Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Contractor",
    "mandatoryStatus": "Mandatory",
    "trigger": "Signed prior to assignment",
    "owner": "Privacy Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-engagement",
    "systemLocation": "public.controlled_documents (DOC-PRV-01, DOC-COC-01)",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PAY-01",
    "name": "Support Worker Weekly Timesheet Record",
    "category": "4. Payroll & Pay Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Completed shifts submitted at end of weekly pay cycle",
    "owner": "Support Worker / Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (Fair Work Act 2009 s535)",
    "systemLocation": "public.timesheets & timesheet_entries / Worker Portal & Admin Timesheets",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PAY-02",
    "name": "Manager Timesheet Approval & Billing Authorisation Audit",
    "category": "4. Payroll & Pay Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Manager approval of submitted timesheet; triggers billing readiness",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (Fair Work Act 2009)",
    "systemLocation": "public.timesheets (approved_at, notes) / Admin TimesheetsTab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PAY-03",
    "name": "Approved Payroll Input Export (External STP Engine)",
    "category": "4. Payroll & Pay Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Weekly / Fortnightly payroll cycle export to Xero/MYOB/Employment Hero STP engine",
    "owner": "Finance & Payroll Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (Tax & Fair Work compliance)",
    "systemLocation": "/api/workforce/payroll/export / Admin TimesheetsTab Export Button",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PAY-04",
    "name": "Statutory Payslip Storage & Worker Portal Access Record",
    "category": "4. Payroll & Pay Documents",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Generated by external STP engine and uploaded within 1 working day of pay (s536 Fair Work Act)",
    "owner": "Finance & Payroll Lead",
    "version": "Per Pay Period",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Per pay run",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (Fair Work Act 2009 s535)",
    "systemLocation": "public.documents (owner_type: staff, category: payslip) / Worker Portal Payslips Tab",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PAY-05",
    "name": "Travel & Mileage Reimbursement Log",
    "category": "4. Payroll & Pay Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Conditional",
    "trigger": "Worker travel in own vehicle during participant support (SCHADS vehicle allowance)",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.timesheet_entries (kilometres, travel_minutes) / Shift Completion Modal",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-FIN-01",
    "name": "NDIS Compliant Service Invoice",
    "category": "5. Finance & Billing Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Plan Manager / NDIA",
    "mandatoryStatus": "Mandatory",
    "trigger": "Generated from approved service records and timesheets",
    "owner": "Finance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (Taxation Administration Act 1953)",
    "systemLocation": "public.invoices & public.invoice_line_items / /api/billing/invoices/[id]/pdf",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY",
    "notes": "Preserves non-registered GST disclaimer: \"INVOICE\" and \"GST has not been charged – supplier is not registered for GST.\""
  },
  {
    "code": "DOC-FIN-02",
    "name": "Participant Service Quote / Estimate",
    "category": "5. Finance & Billing Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Optional",
    "trigger": "Intake budget planning or requested quote by Support Coordinator",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.quotes & public.quote_line_items / CRM Quotes Tab",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-FIN-03",
    "name": "Billing Batch Summary & Plan Manager Remittance Advice",
    "category": "5. Finance & Billing Documents",
    "documentClass": "A. GENERATED DOCUMENT",
    "audience": "Plan Manager / NDIA",
    "mandatoryStatus": "Mandatory",
    "trigger": "Generated during weekly billing run for submission to Plan Managers",
    "owner": "Finance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.invoices & public.invoice_line_items / CRM Invoicing Tab",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Individual invoice PDFs and service records are operational via public.invoices; multi-invoice batch bundling and remittance reconciliation are handled externally or uploaded to public.documents."
  },
  {
    "code": "DOC-FIN-04",
    "name": "Pricing Schedule, Travel & Cancellation Policy",
    "category": "5. Finance & Billing Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Public disclosure and onboarding schedule attachment",
    "owner": "Finance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-PRC-01) / /documents/pricing-travel-cancellation",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-FIN-05",
    "name": "Provider Direct Remittance & Bank Details Record",
    "category": "5. Finance & Billing Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Secured admin configuration; printed on service invoices",
    "owner": "Proprietor",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent operational record",
    "systemLocation": "public.provider_config (bank_name, bsb, account_number, account_name) / Admin Settings",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SRV-01",
    "name": "Shift Booking, Roster & Assignment Record",
    "category": "6. Service Delivery Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Rostered by admin; subject to worker readiness gating",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.shifts & shift_assignments / CRM Shifts & Worker Portal",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SRV-02",
    "name": "Support Shift Progress Note & Goal Rating Record",
    "category": "6. Service Delivery Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory completion by support worker at conclusion of shift",
    "owner": "Support Worker",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.shift_progress_notes & public.goal_progress_notes / Worker Portal",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SRV-03",
    "name": "Service Record & Billing Verification Entry",
    "category": "6. Service Delivery Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Created automatically upon shift completion; approved via timesheet",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.service_records / CRM Billing & Service Delivery Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SRV-04",
    "name": "Short Notice Cancellation Record",
    "category": "6. Service Delivery Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Conditional",
    "trigger": "Participant cancellation without schedule-required notice",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.service_records (cancellation_reason, is_short_notice) / CRM Billing",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY",
    "notes": "Short notice cancellation claiming complies with NDIS Pricing Arrangements and agreed schedule terms where worker cannot be reassigned."
  },
  {
    "code": "DOC-SRV-05",
    "name": "Worker Shift Handover & Escalation Note",
    "category": "6. Service Delivery Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Conditional",
    "trigger": "Back-to-back shift transitions or emergent follow-up required",
    "owner": "Support Worker",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.shift_progress_notes (follow_up_required, follow_up_notes) / Worker Portal",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-01",
    "name": "Participant Safeguarding & Zero-Tolerance Policy",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Operational standard; acknowledged by all staff and participants",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-SFG-01) / /documents/safeguarding-policy",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-02",
    "name": "Incident Report & Risk Assessment Record",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Within 24 hours of any accident, injury, allegation or unexpected event",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (NDIS Incident Management Rules)",
    "systemLocation": "public.incidents / Worker Portal & CRM Incidents Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-03",
    "name": "Reportable Incident Assessment & Commission Notification Record",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Immediate triage and internal management assessment; statutory reporting assessment required",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.incidents (is_reportable, commission_reference) / CRM Incidents Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY",
    "notes": "Unregistered provider governance: internal management assessment evaluates any statutory notifications (Police, SafeWork NSW, or lead registered provider intermediary obligations)."
  },
  {
    "code": "DOC-SFG-04",
    "name": "Participant Complaint & Feedback Register Entry",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Receipt of complaint via website, phone, email or portal",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years (NDIS Complaints Management Resolution Rules)",
    "systemLocation": "public.complaints / /complaints & CRM Complaints Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-05",
    "name": "Complaints, Feedback & Dispute Resolution Guide",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Delivered at onboarding and publicly accessible",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-CMP-01) / /complaints",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-06",
    "name": "Incident Management & Safeguarding Guide",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Published governance document and onboarding standard",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-INC-01) / /incident-management",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-SFG-07",
    "name": "Corrective & Preventative Action (CAPA) Plan Record",
    "category": "7. Safeguarding & Quality Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Root-cause analysis following high-severity incidents or substantiated complaints",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.corrective_actions / CRM Safeguarding Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WHS-01",
    "name": "Work Health & Safety (WHS) and Hazard Policy",
    "category": "8. WHS & Safety Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory onboarding policy for all staff and contractors",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-WHS-01) / /documents/whs-policy",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WHS-02",
    "name": "Home & Community Environment Hazard Inspection",
    "category": "8. WHS & Safety Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Prior to first service delivery in participant home; annual review",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.risk_assessments (hazard_type: environment) / CRM Risk Assessments & /api/governance/whs",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WHS-03",
    "name": "Lone Worker & Community Safety Protocol",
    "category": "8. WHS & Safety Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory reading for all workers delivering 1:1 in-home supports",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-LNE-01) / /documents/lone-worker-policy",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WHS-04",
    "name": "Infection Prevention & Hygiene Protocol",
    "category": "8. WHS & Safety Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Operational hygiene standard; mandatory induction",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-IPC-01) / /documents/infection-prevention",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-WHS-05",
    "name": "Manual Handling & Ergonomics Standard",
    "category": "8. WHS & Safety Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Induction training and annual competency review",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-MNH-01) / /documents/manual-handling",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRN-01",
    "name": "Participant Transport & Vehicle Safety Standard",
    "category": "9. Vehicle & Transport Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory for any worker conducting community access or participant transport",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-TRN-01) / /documents/transport-safety",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRN-02",
    "name": "Worker Driver Licence Verification Record",
    "category": "9. Vehicle & Transport Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Verified prior to shift assignment involving driving",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Licence expiry date",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (requirement_code: valid_driver_licence)",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRN-03",
    "name": "Comprehensive / Business Vehicle Insurance Certificate",
    "category": "9. Vehicle & Transport Records",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Required if worker transports participants in private vehicle",
    "owner": "Support Worker / Operations Lead",
    "version": "Annual",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Policy expiry date",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.worker_credentials (vehicle_insurance_comprehensive, business_use_insurance)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRN-04",
    "name": "Vehicle Registration & Roadworthiness Declaration",
    "category": "9. Vehicle & Transport Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Annual verification for transport-assigned workers",
    "owner": "Operations Lead",
    "version": "Annual",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Registration renewal date",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.worker_credentials (vehicle_registration, vehicle_roadworthiness)",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRN-05",
    "name": "Participant Transport Agreement & Activity Consent",
    "category": "9. Vehicle & Transport Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Mandatory",
    "trigger": "Part of Schedule of Supports & Intake agreement",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.document_templates (DOC-PART-02) / Schedule of Supports transport clause",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-GOV-01",
    "name": "Business Continuity & Disaster Recovery Plan",
    "category": "10. Governance & Business Operational Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Annual board/owner review and contingency activation",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent operational record",
    "systemLocation": "public.controlled_documents (DOC-BCP-01) / /documents/business-continuity",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-GOV-02",
    "name": "Conflict of Interest Policy & Register",
    "category": "10. Governance & Business Operational Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Onboarding declaration and ongoing change disclosure",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-COI-01) / /documents/conflict-of-interest",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-GOV-03",
    "name": "Money Handling & Financial Integrity Protocol",
    "category": "10. Governance & Business Operational Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory protocol governing participant cash/card assistance during outings",
    "owner": "Finance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-MNY-01) / /documents/money-handling",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-GOV-04",
    "name": "Records Retention, Disposal & Archival Policy",
    "category": "10. Governance & Business Operational Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Governance standard governing digital records, backups, and disposal logs",
    "owner": "Privacy Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent operational record",
    "systemLocation": "public.controlled_documents (DOC-REC-01) / /documents/records-retention",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-GOV-05",
    "name": "Controlled Document Register & Review Audit",
    "category": "10. Governance & Business Operational Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Continuously active system register with automated version tracking",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent system metadata",
    "systemLocation": "public.controlled_documents / /api/governance/document-register",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-REG-01",
    "name": "ABN & Business Registration Certificate (Opus Care Support Services)",
    "category": "11. Regulatory & Unregistered Provider Evidence",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Maintained on public register (ABN 41 267 197 576)",
    "owner": "Australian Business Register (ABR)",
    "version": "Active",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Ongoing ABR verification",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent business record",
    "systemLocation": "ABR Public Register / Admin Settings (ABN 41 267 197 576)",
    "officialUrl": "https://abr.business.gov.au/ABN/View?abn=41267197576",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-REG-02",
    "name": "Unregistered Provider Scope & Declaration Statement",
    "category": "11. Regulatory & Unregistered Provider Evidence",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Publicly declared on website footer, service agreement, and invoices",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent record",
    "systemLocation": "public.controlled_documents (DOC-AGR-01) / /about & /compliance",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-REG-03",
    "name": "Business Insurance Register (Public Liability, Professional Indemnity)",
    "category": "11. Regulatory & Unregistered Provider Evidence",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Self-service entry by owner upon policy purchase; fail-closed gate",
    "owner": "Proprietor",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual policy renewal",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-expiry",
    "systemLocation": "public.organisation_insurance & public.provider_config / Admin Settings Insurance Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Architecture complete and operational; awaiting owner real-world policy purchase (status: PENDING). Paid service delivery remains fail-closed."
  },
  {
    "code": "DOC-REG-04",
    "name": "NDIS Commission Worker Screening Database (NWSD) Registration Record",
    "category": "11. Regulatory & Unregistered Provider Evidence",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Required for employer linking and real-time NDIS worker screening clearance checks",
    "owner": "NDIS Quality and Safeguards Commission",
    "version": "Current NWSD Portal",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Continuous portal link",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent operational record",
    "systemLocation": "NDIS Commission Portal / Worker Readiness Panel screening status",
    "officialUrl": "https://www.ndiscommission.gov.au/providers/worker-screening",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-REG-05",
    "name": "NDIS Pricing Arrangements Compliance Register",
    "category": "11. Regulatory & Unregistered Provider Evidence",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Annual update aligned with NDIA Price Limits (2026-27)",
    "owner": "Finance Lead",
    "version": "2026-27.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.controlled_documents (DOC-PRC-01) / lib/ndisCatalogue.ts",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-AUD-01",
    "name": "Continuous Improvement Register & Action Log",
    "category": "12. Continuous Improvement & Audit Evidence",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Quarterly review or triggered by audits, feedback, and CAPA completions",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.corrective_actions & public.audit_events / CRM Safeguarding Tab",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-AUD-02",
    "name": "Internal Quality & Compliance Audit Checklist",
    "category": "12. Continuous Improvement & Audit Evidence",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Conducted bi-annually across participant files and worker credentials",
    "owner": "Operations & Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.audit_events & public.corrective_actions / Admin Audit Trail",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Audit logging and CAPA tracking operational in CRM; periodic internal compliance checklists are conducted manually against governance guidelines."
  },
  {
    "code": "DOC-AUD-03",
    "name": "System Mutation & Operational Audit Log",
    "category": "12. Continuous Improvement & Audit Evidence",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Mandatory",
    "trigger": "Automated immutability log on every admin, worker, and participant mutation",
    "owner": "Privacy & Security Officer",
    "version": "Continuous",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Continuous",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years minimum",
    "systemLocation": "public.audit_events / Admin Audit Trail API",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-AUD-04",
    "name": "Participant Feedback Survey & Outcome Report",
    "category": "12. Continuous Improvement & Audit Evidence",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Participant / Nominee",
    "mandatoryStatus": "Conditional",
    "trigger": "Annual or post-support milestone satisfaction evaluation",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.complaints & public.participant_goals / CRM Client Feedback",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "PARTIAL",
    "notes": "Continuous feedback captured via complaints and goal reviews; standalone survey forms and periodic outcome reports are administered manually."
  },
  {
    "code": "DOC-PUB-01",
    "name": "Public Website & Service Scope Information",
    "category": "13. Marketing, Public & Information Notices",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Live public deployment (https://opuscare.com.au)",
    "owner": "Proprietor",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Live web deployment history (Git)",
    "systemLocation": "Next.js App Router (app/page.tsx, /services, /about)",
    "officialUrl": "https://opuscare.com.au",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PUB-02",
    "name": "Public Privacy Policy & Privacy Collection Notice",
    "category": "13. Marketing, Public & Information Notices",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Public web disclosure in accordance with Privacy Act 1988 (APPs)",
    "owner": "Privacy Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent policy history",
    "systemLocation": "public.controlled_documents (DOC-PRV-01) / /privacy",
    "officialUrl": "https://opuscare.com.au/privacy",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PUB-03",
    "name": "Public Complaints & Feedback Channel Guide",
    "category": "13. Marketing, Public & Information Notices",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Public web disclosure including direct NDIS Commission escalation details",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent policy history",
    "systemLocation": "public.controlled_documents (DOC-CMP-01) / /complaints",
    "officialUrl": "https://opuscare.com.au/complaints",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PUB-04",
    "name": "Public Incident Management & Safeguarding Statement",
    "category": "13. Marketing, Public & Information Notices",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Public web disclosure outlining open disclosure and participant protections",
    "owner": "Safeguarding Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent policy history",
    "systemLocation": "public.controlled_documents (DOC-INC-01) / /incident-management",
    "officialUrl": "https://opuscare.com.au/incident-management",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-PUB-05",
    "name": "Public Pricing & Cancellation Schedule",
    "category": "13. Marketing, Public & Information Notices",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Public web disclosure of standard hourly rates, travel rules and cancellation criteria",
    "owner": "Finance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent policy history",
    "systemLocation": "public.controlled_documents (DOC-PRC-01) / /documents/pricing-travel-cancellation",
    "officialUrl": "https://opuscare.com.au/documents/pricing-travel-cancellation",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRG-01",
    "name": "NDIS Worker Orientation Module Certificate (Quality, Safety & You)",
    "category": "14. Training & Competency Records",
    "documentClass": "D. OFFICIAL EXTERNAL / GOVERNMENT DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory NDIS Commission orientation module completion prior to service delivery",
    "owner": "NDIS Quality and Safeguards Commission",
    "version": "Current",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Initial completion certificate",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (worker_orientation) / Worker Readiness Panel",
    "officialUrl": "https://training.ndiscommission.gov.au/",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "EXTERNAL-OFFICIAL"
  },
  {
    "code": "DOC-TRG-02",
    "name": "Provide First Aid (HLTAID011) & CPR (HLTAID009) Certificate",
    "category": "14. Training & Competency Records",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Mandatory accredited first aid qualification prior to roster activation",
    "owner": "Accredited RTO / Worker",
    "version": "Current Standard",
    "effectiveDate": "2026-07-01",
    "reviewDate": "First Aid: 3 years; CPR: 12 months",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (first_aid, cpr) / Worker Readiness Panel",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRG-03",
    "name": "Manual Handling & Safe Ergonomics Competency Sign-Off",
    "category": "14. Training & Competency Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Verified assessment prior to roster activation and annual practical review",
    "owner": "WHS Officer",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (manual_handling) & worker_competencies",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRG-04",
    "name": "Medication Assistance Standard (Non-Clinical Prompting)",
    "category": "14. Training & Competency Records",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Conditional",
    "trigger": "Verified before worker assists participant with pre-packaged Webster pack prompting",
    "owner": "Care Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "Annual",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.controlled_documents (DOC-MED-01) / /documents/medication-assistance",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-TRG-05",
    "name": "Internal Training Course Module & Quiz Completion Record",
    "category": "14. Training & Competency Records",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Mandatory",
    "trigger": "Completed via Worker Portal Training Tab upon assignment",
    "owner": "Operations Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.training_courses & public.training_completions / Worker Portal",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CLN-01",
    "name": "Clinical Governance & Scope-of-Practice Standard",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Public / All",
    "mandatoryStatus": "Mandatory",
    "trigger": "Governing baseline defining strict non-clinical boundary for unregistered operations",
    "owner": "Clinical Governance Lead",
    "version": "2026.1",
    "effectiveDate": "2026-07-01",
    "reviewDate": "2027-06-30",
    "acknowledgementRequired": true,
    "signatureRequired": false,
    "retentionRecordStatus": "Permanent governance record",
    "systemLocation": "public.controlled_documents (DOC-CLN-01) / /documents/clinical-scope",
    "templateAvailable": true,
    "generationAvailable": true,
    "storageAvailable": true,
    "status": "READY"
  },
  {
    "code": "DOC-CLN-02",
    "name": "High-Intensity Daily Personal Activities Service Module",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "C. CONTROLLED POLICY",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Disabled until Clinical Lead RN appointed and AHPRA verified",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years from activation",
    "systemLocation": "public.clinical_service_readiness & public.service_scope_registry",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED",
    "notes": "Fail-closed: High-intensity supports cannot be rostered or billed until clinical governance gate is unlocked by owner."
  },
  {
    "code": "DOC-CLN-03",
    "name": "Enteral Feeding (PEG) Support Plan & Competency Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires tube feeding support",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (enteral_feeding_peg)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-04",
    "name": "Bowel Care Management Plan & Delegation Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires invasive bowel management",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (bowel_care_invasive)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-05",
    "name": "Tracheostomy & Ventilator Support Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires airway suctioning or ventilator management",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (tracheostomy_airway)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-06",
    "name": "Subcutaneous Injection & Clinical Medication Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires injection or complex dose administration",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (subcutaneous_injections)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-07",
    "name": "Complex Wound Management Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires dressing of surgical/pressure wounds",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (wound_management_complex)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-08",
    "name": "Indwelling / Suprapubic Catheter Care Protocol",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Support Worker",
    "mandatoryStatus": "Future",
    "trigger": "Participant requires invasive urinary catheter management",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Upon Activation",
    "acknowledgementRequired": true,
    "signatureRequired": true,
    "retentionRecordStatus": "7 years post-service",
    "systemLocation": "public.competency_catalogue (urinary_catheter_invasive)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": false,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-09",
    "name": "AHPRA Registered Nurse Credential Verification Record",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "B. CRM STRUCTURED RECORD / FORM",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Future",
    "trigger": "Required when appointing Clinical Nurse Lead",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Annual AHPRA registration",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years post-employment",
    "systemLocation": "public.worker_credentials (ahpra_nursing)",
    "templateAvailable": true,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "FUTURE / CLINICAL-DISABLED"
  },
  {
    "code": "DOC-CLN-10",
    "name": "Clinical Malpractice & Professional Indemnity Policy Record",
    "category": "15. Clinical & High-Intensity Transition Documents",
    "documentClass": "E. EVIDENCE / UPLOADED DOCUMENT",
    "audience": "Admin / Operations",
    "mandatoryStatus": "Future",
    "trigger": "Required prior to enabling high-intensity clinical activities",
    "owner": "Clinical Governance Lead",
    "version": "Draft / Future 2026",
    "effectiveDate": "Future Activation",
    "reviewDate": "Annual policy renewal",
    "acknowledgementRequired": false,
    "signatureRequired": false,
    "retentionRecordStatus": "7 years",
    "systemLocation": "public.worker_credentials (clinical_indemnity)",
    "templateAvailable": false,
    "generationAvailable": false,
    "storageAvailable": true,
    "status": "FUTURE / CLINICAL-DISABLED"
  }
];

export function getMasterDocumentRegister(filters?: {
  category?: string;
  status?: string;
  documentClass?: string;
  audience?: string;
  search?: string;
}): MasterDocumentItem[] {
  return MASTER_DOCUMENT_REGISTER.filter((item) => {
    if (filters?.category && item.category !== filters.category) return false;
    if (filters?.status && item.status !== filters.status) return false;
    if (filters?.documentClass && item.documentClass !== filters.documentClass) return false;
    if (filters?.audience && item.audience !== filters.audience) return false;
    if (filters?.search) {
      const q = filters.search.toLowerCase();
      return (
        item.code.toLowerCase().includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.trigger.toLowerCase().includes(q) ||
        item.systemLocation.toLowerCase().includes(q)
      );
    }
    return true;
  });
}

export function getDocumentByCode(code: string): MasterDocumentItem | undefined {
  return MASTER_DOCUMENT_REGISTER.find((item) => item.code === code);
}

export function getDocumentsByCategory(category: DocumentCategory): MasterDocumentItem[] {
  return MASTER_DOCUMENT_REGISTER.filter((item) => item.category === category);
}

export function getMasterDocumentSummary() {
  const total = MASTER_DOCUMENT_REGISTER.length;
  const ready = MASTER_DOCUMENT_REGISTER.filter((d) => d.status === 'READY').length;
  const externalOfficial = MASTER_DOCUMENT_REGISTER.filter((d) => d.status === 'EXTERNAL-OFFICIAL').length;
  const partial = MASTER_DOCUMENT_REGISTER.filter((d) => d.status === 'PARTIAL').length;
  const missing = MASTER_DOCUMENT_REGISTER.filter((d) => d.status === 'MISSING').length;
  const clinicalDisabled = MASTER_DOCUMENT_REGISTER.filter((d) => d.status === 'FUTURE / CLINICAL-DISABLED').length;
  const operationalCount = ready + externalOfficial;
  const templateCount = MASTER_DOCUMENT_REGISTER.filter((d) => d.templateAvailable).length;

  const byCategory: Record<string, number> = {};
  for (const doc of MASTER_DOCUMENT_REGISTER) {
    byCategory[doc.category] = (byCategory[doc.category] || 0) + 1;
  }

  const byClass: Record<string, number> = {};
  for (const doc of MASTER_DOCUMENT_REGISTER) {
    byClass[doc.documentClass] = (byClass[doc.documentClass] || 0) + 1;
  }

  return {
    totalDocuments: total,
    readyCount: ready,
    externalOfficialCount: externalOfficial,
    partialCount: partial,
    missingCount: missing,
    clinicalDisabledCount: clinicalDisabled,
    operationalCount,
    templateCount,
    operationalCompletenessPct: Math.round(((ready + externalOfficial) / (total - clinicalDisabled)) * 100),
    byCategory,
    byClass,
  };
}

