import { CheckCircle2, HeartHandshake, ShieldCheck, Users } from 'lucide-react';
import Link from 'next/link';
import { SiteHeader } from '../../components/SiteHeader';
import { SiteFooter } from '../../components/SiteFooter';

export default function AboutPage(){return <><SiteHeader/><main>
<section className="pageHero shell"><span className="eyebrow">About CarePoint</span><h1>A smaller support service with professional standards.</h1><p>CarePoint Support Services is being built around dependable relationships, clear communication and practical support that respects each participant’s choices, routines and goals.</p></section>
<section className="split shell aboutPageSplit"><div className="aboutVisual"><div className="quoteCard"><HeartHandshake/><p>Support should fit the person — not the other way around.</p><span>CarePoint principle</span></div></div><div className="aboutCopy"><span className="eyebrow">Our approach</span><h2>Listen first. Agree clearly. Support consistently.</h2><p>We want participants and families to know who they are dealing with, what has been agreed, what it costs and what happens if something changes.</p><ul><li><CheckCircle2/>Choice and control in day-to-day support</li><li><CheckCircle2/>Respect for privacy, culture, identity and communication preferences</li><li><CheckCircle2/>Clear service agreements, boundaries and pricing</li><li><CheckCircle2/>Simple complaints and feedback pathways</li><li><CheckCircle2/>Incident awareness, risk management and continuous improvement</li></ul></div></section>
<section className="softSection"><div className="shell valuesGrid"><article><Users/><h3>Person-centred</h3><p>Support is shaped around the participant’s goals and preferences rather than a one-size-fits-all routine.</p></article><article><ShieldCheck/><h3>Safe & accountable</h3><p>We are building practical systems for screening, records, privacy, incidents, feedback and risk.</p></article><article><HeartHandshake/><h3>Reliable relationships</h3><p>Good disability support depends on trust, consistency, respectful communication and follow-through.</p></article></div></section>
<section className="shell contentBand"><div><span className="eyebrow">Current business stage</span><h2>Transparent while we build.</h2></div><div><p>CarePoint is currently being established as an unregistered provider model for self-managed and plan-managed participants. The website will not display an NDIS registered-provider badge, insurance limits, qualifications, locations or service claims until those details are confirmed.</p><Link className="inlineCta" href="/referral">Discuss a referral →</Link></div></section>
</main><SiteFooter/></>}
